"""Generate 98_glossary.md from the "Key terms" table in every guide's Introduction.

Usage:
    python tools/build_glossary.py          # (re)write 98_glossary.md
    python tools/build_glossary.py --check  # exit 1 if 98_glossary.md is out of date (used in CI)
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "98_glossary.md"
GUIDE_RE = re.compile(r"^(\d\d)_[a-z0-9-]+\.md$")
ROW_RE = re.compile(r"^\|\s*(.+?)\s*\|\s*(.+?)\s*\|$")

HEADER = """# 98 - Glossary

Every key term from the Introductions of all guides, A to Z, with a link to the guide that explains it. Generated by `tools/build_glossary.py` from the "Key terms" tables; do not edit by hand.

Some terms appear in several guides with a meaning specific to that context (for example "Token" in HTTP authentication and in LLMs).
"""


def guide_title(path: Path) -> str:
    first = path.read_text(encoding="utf-8").splitlines()[0]
    return first.removeprefix("# ")


def key_terms(path: Path) -> list[tuple[str, str]]:
    """Rows of the table that directly follows '### Key terms'."""
    lines = path.read_text(encoding="utf-8").splitlines()
    try:
        start = lines.index("### Key terms")
    except ValueError:
        return []
    rows, in_table = [], False
    for line in lines[start + 1:]:
        if line.startswith("|"):
            in_table = True
            m = ROW_RE.match(line)
            if m and not set(m.group(1)) <= {"-"} and m.group(1) != "Term":
                rows.append((m.group(1), m.group(2)))
        elif in_table:
            break
    return rows


def sort_key(term: str) -> str:
    return re.sub(r"[^a-z0-9]", "", term.lower()) or term.lower()


def first_letter(term: str) -> str:
    ch = sort_key(term)[:1].upper()
    return ch if ch.isalpha() else "#"


def build() -> str:
    by_letter: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for path in sorted(ROOT.glob("*.md")):
        if not GUIDE_RE.match(path.name) or path.name == OUT.name:
            continue
        link = f"[{guide_title(path)}]({path.name})"
        for term, meaning in key_terms(path):
            by_letter[first_letter(term)].append((term, meaning, link))

    letters = sorted(by_letter, key=lambda c: (c != "#", c))
    parts = [HEADER, "Jump to: " + " ".join(f"[{c}](#{c.lower() if c != '#' else 'symbols-and-numbers'})" for c in letters), ""]
    for letter in letters:
        parts.append(f"## {letter if letter != '#' else 'Symbols and numbers'}")
        parts.append("")
        parts.append("| Term | Meaning | Guide |")
        parts.append("|---|---|---|")
        for term, meaning, link in sorted(by_letter[letter], key=lambda r: (sort_key(r[0]), r[2])):
            parts.append(f"| {term} | {meaning} | {link} |")
        parts.append("")
    return "\n".join(parts)


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n") if OUT.exists() else ""
        if current != content:
            print("98_glossary.md is out of date: run python tools/build_glossary.py")
            return 1
        print("98_glossary.md is up to date")
        return 0
    OUT.write_text(content, encoding="utf-8", newline="\n")
    terms = content.count("\n| ") - content.count("\n| Term |")
    print(f"Wrote {OUT.name} with {terms} terms")
    return 0


if __name__ == "__main__":
    sys.exit(main())
